[package]
name = "johnston-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
johnston = {path = "../johnston"}

[dev-dependencies]
assert_cmd = "2.0.0"
